-- Crear una estuctura de roles en medallion para este caso? 
-- Para mantener separados los roles que tienen acceso a los secretos y a github
-- yo creo que si, para mantenerlos con responsabilidades limitadas 
-- o lo mantenemos bajo la administracion del role ya creado para soporte? 


-- 1. Create a secret with credentials for authenticating

-- Base de datos: RP_BRONZE_PROD
-- Esquema: RP_SNOWFLAKE_ADMINISTRATOR
-- Role: BD_SU_SECRET_ADMIN_ROLE
-- Secreto: BD_SNOWFLAKE_INTEGRATION_git_secret


CREATE DATABASE IF NOT EXISTS RP_BRONZE_PROD;
CREATE SCHEMA DATABASE IF NOT EXISTS RP_BRONZE_PROD.RP_SNOWFLAKE_ADMINISTRATOR;

USE ROLE ACCOUNTADMIN;
CREATE ROLE BD_SU_SECRET_ADMIN_ROLE COMMENT = 'Role for managing secrets';
GRANT CREATE SECRET ON SCHEMA RP_BRONZE_PROD.RP_SNOWFLAKE_ADMINISTRATOR TO ROLE BD_SU_SECRET_ADMIN_ROLE;

USE ROLE BD_SU_SECRET_ADMIN_ROLE;
GRANT USAGE ON DATABASE RP_BRONZE_PROD TO ROLE BD_SU_SECRET_ADMIN_ROLE;
GRANT USAGE ON SCHEMA RP_BRONZE_PROD.RP_SNOWFLAKE_ADMINISTRATOR TO ROLE BD_SU_SECRET_ADMIN_ROLE;

USE ROLE BD_SU_SECRET_ADMIN_ROLE;
USE DATABASE RP_BRONZE_PROD;
USE SCHEMA RP_BRONZE_PROD.RP_SNOWFLAKE_ADMINISTRATOR;

CREATE OR REPLACE SECRET BD_SNOWFLAKE_INTEGRATION_GIT_SECRET
  TYPE = password
  USERNAME = '******'  -- Replace with your credentials
  PASSWORD = '******'; -- Replace with your credentials


-- 2. Create an API integration for interacting with the repository API

USE ROLE ACCOUNTADMIN;
CREATE ROLE BD_SU_GITHUB_ADMIN_ROLE;
GRANT CREATE INTEGRATION ON ACCOUNT TO ROLE BD_SU_GITHUB_ADMIN_ROLE;

GRANT USAGE ON DATABASE RP_BRONZE_PROD TO ROLE BD_SU_GITHUB_ADMIN_ROLE;
GRANT USAGE ON SCHEMA RP_BRONZE_PROD.RP_SNOWFLAKE_ADMINISTRATOR TO ROLE BD_SU_GITHUB_ADMIN_ROLE;

USE ROLE BD_SU_SECRET_ADMIN_ROLE;
GRANT USAGE ON SECRET BD_SNOWFLAKE_INTEGRATION_GIT_SECRET TO ROLE BD_SU_GITHUB_ADMIN_ROLE;

USE ROLE BD_SU_GITHUB_ADMIN_ROLE;
USE DATABASE RP_BRONZE_PROD;
USE SCHEMA RP_BRONZE_PROD.RP_SNOWFLAKE_ADMINISTRATOR;

CREATE OR REPLACE API INTEGRATION RP_SNOWFLAKE_INTEGRATION_GIT
  API_PROVIDER = git_https_api
  API_ALLOWED_PREFIXES = ('https://github.com/Cjaimesg/snowflake-git-integration')
  ALLOWED_AUTHENTICATION_SECRETS = (BD_SNOWFLAKE_INTEGRATION_GIT_SECRET)
  ENABLED = TRUE;

-- 3. Create a Git repository stage and clone the repository
USE ROLE ACCOUNTADMIN;
GRANT CREATE GIT REPOSITORY ON SCHEMA RP_BRONZE_PROD.RP_SNOWFLAKE_ADMINISTRATOR TO ROLE BD_SU_GITHUB_ADMIN_ROLE;

USE ROLE BD_SU_GITHUB_ADMIN_ROLE;

CREATE OR REPLACE GIT REPOSITORY RP_SNOWFLAKE_INTEGRATION_GITHUB
  API_INTEGRATION = RP_SNOWFLAKE_INTEGRATION_GIT
  GIT_CREDENTIALS = BD_SNOWFLAKE_INTEGRATION_GIT_SECRET
  ORIGIN = 'https://github.com/Cjaimesg/snowflake-git-integration.git';


-- 4. Git operations in Snowflake

ALTER GIT REPOSITORY RP_SNOWFLAKE_INTEGRATION_GITHUB FETCH;
SHOW GIT BRANCHES IN RP_SNOWFLAKE_INTEGRATION_GITHUB;