name: snowflake_cicd_pipeline
 
on:
  push:
    branches:
      - main
    paths:
      - 'demo_project/**'
 
  # Permite ejecutar este workflow manualmente desde la pestaña Actions
  workflow_dispatch:
    inputs:
      environment:
        type: choice
        description: 'Selecciona el entorno'
        required: true
        default: 'DEV'
        options:
          - DEV
          - TST
          - PRD
 
permissions:
      id-token: write
      contents: read
 
jobs:
  deploy:
    runs-on: ubuntu-latest
 
    steps:
      # Verifica el repositorio
      - name: Checkout repository
        uses: actions/checkout@v3
        with:
          fetch-depth: 2
 
      # Instalación de Snowflake CLI
      - name: Snowflake CLI Installation
        uses: Snowflake-Labs/snowflake-cli-action@v1.5
        with:
          cli-version: "latest"
          default-config-file-path: "config.toml"
      
      # Obtener solo los archivos modificados con extensión .sql
      - name: Get modified files
        id: get_files
        run: |
          # Obtener solo los archivos modificados con extensión .sql
          git diff --name-only HEAD^ HEAD | grep '\.sql$' > modified_files.txt || true
          cat modified_files.txt
          echo "files=$(cat modified_files.txt | tr '\n' ' ')" >> $GITHUB_ENV
 
      # ============ DEV ============
      - name: Deploy Snowflake objects to DEV
        if: ${{ github.event_name == 'push' || (github.event_name == 'workflow_dispatch' && github.event.inputs.environment == 'DEV') }}
        env:
          SNOWFLAKE_CONNECTIONS_ACCOUNT: ${{ secrets.SNOWFLAKE_CONNECTIONS_ACCOUNT }}
          SNOWFLAKE_CONNECTIONS_USER: ${{ secrets.SNOWFLAKE_CONNECTIONS_USER }}
          SNOWFLAKE_CONNECTION_PASSWORD: ${{ secrets.SNOWFLAKE_CONNECTION_PASSWORD }}
          SNOWFLAKE_CONNECTIONS_ROLES: ${{ secrets.SNOWFLAKE_CONNECTIONS_ROLES }}
          SNOWFLAKE_CONNECTION_WAREHOUSE: ${{ secrets.SNOWFLAKE_CONNECTION_WAREHOUSE }}
          SNOWFLAKE_CONNECTIONS_DATABASE: ${{ secrets.SNOWFLAKE_CONNECTIONS_DATABASE }}
          SNOWFLAKE_CONNECTIONS_SCHEMA: ${{ secrets.SNOWFLAKE_CONNECTIONS_SCHEMA }}
        run: |
          # Actualizar repositorio en Snowflake 
          echo "Fetching repository to Snowflake"
          snow sql -q "ALTER GIT REPOSITORY snowflake_extensions FETCH" \
            --account $SNOWFLAKE_CONNECTIONS_ACCOUNT \
            --user $SNOWFLAKE_CONNECTIONS_USER \
            --password $SNOWFLAKE_CONNECTION_PASSWORD \
            --role $SNOWFLAKE_CONNECTIONS_ROLES \
            --warehouse $SNOWFLAKE_CONNECTION_WAREHOUSE \
            --database $SNOWFLAKE_CONNECTIONS_DATABASE \
            --schema $SNOWFLAKE_CONNECTIONS_SCHEMA

          # Obtener archivos modificados con extensión .sql
          # modified_files=$(git diff --name-only HEAD^ HEAD | grep '\.sql$')
          # Iterar sobre los archivos y ejecutar el comando por cada uno
          for file in ${{ env.files }}; do
            snow sql -q "EXECUTE IMMEDIATE FROM @snowflake_extensions/branches/main/$file USING (ENV => 'DEV')" \
              --account $SNOWFLAKE_CONNECTIONS_ACCOUNT \
              --user $SNOWFLAKE_CONNECTIONS_USER \
              --password $SNOWFLAKE_CONNECTION_PASSWORD \
              --role $SNOWFLAKE_CONNECTIONS_ROLES \
              --warehouse $SNOWFLAKE_CONNECTION_WAREHOUSE \
              --database $SNOWFLAKE_CONNECTIONS_DATABASE \
              --schema $SNOWFLAKE_CONNECTIONS_SCHEMA \
              --query_tags Test
          done
 
      # ============ TEST ============
      - name: Deploy Snowflake objects to TST
        if: ${{ github.event_name == 'workflow_dispatch' && github.event.inputs.environment == 'TST' }}
        env:
          SNOWFLAKE_CONNECTIONS_ACCOUNT: ${{ secrets.SNOWFLAKE_CONNECTIONS_ACCOUNT }}
          SNOWFLAKE_CONNECTIONS_USER: ${{ secrets.SNOWFLAKE_CONNECTIONS_USER }}
          SNOWFLAKE_CONNECTION_PASSWORD: ${{ secrets.SNOWFLAKE_CONNECTION_PASSWORD }}
          SNOWFLAKE_CONNECTIONS_ROLES: ${{ secrets.SNOWFLAKE_CONNECTIONS_ROLES }}
          SNOWFLAKE_CONNECTION_WAREHOUSE: ${{ secrets.SNOWFLAKE_CONNECTION_WAREHOUSE }}
          SNOWFLAKE_CONNECTIONS_DATABASE: ${{ secrets.SNOWFLAKE_CONNECTIONS_DATABASE }}
          SNOWFLAKE_CONNECTIONS_SCHEMA: ${{ secrets.SNOWFLAKE_CONNECTIONS_SCHEMA }}
        run: |
          snow sql -q "ALTER GIT REPOSITORY snowflake_extensions FETCH" \
            --temporary-connection \
            --account $SNOWFLAKE_CONNECTIONS_ACCOUNT \
            --user $SNOWFLAKE_CONNECTIONS_USER \
            --password $SNOWFLAKE_CONNECTION_PASSWORD \
            --role "$SNOWFLAKE_CONNECTIONS_ROLES" \
            --warehouse $SNOWFLAKE_CONNECTION_WAREHOUSE \
            --database $SNOWFLAKE_CONNECTIONS_DATABASE \
            --schema $SNOWFLAKE_CONNECTIONS_SCHEMA
 
          snow sql -q "EXECUTE IMMEDIATE FROM @snowflake_extensions/branches/main/demo_project/sf_deploy_tst.sql" --temporary-connection --account $SNOWFLAKE_CONNECTIONS_ACCOUNT --user $SNOWFLAKE_CONNECTIONS_USER --password $SNOWFLAKE_CONNECTION_PASSWORD --role "$SNOWFLAKE_CONNECTIONS_ROLES" --warehouse $SNOWFLAKE_CONNECTION_WAREHOUSE --database $SNOWFLAKE_CONNECTIONS_DATABASE --schema $SNOWFLAKE_CONNECTIONS_SCHEMA
 
      # ============ PROD ============
      - name: Deploy Snowflake objects to PRD
        if: ${{ github.event_name == 'workflow_dispatch' && github.event.inputs.environment == 'PRD' }}
        env:
          SNOWFLAKE_CONNECTIONS_ACCOUNT: ${{ secrets.SNOWFLAKE_CONNECTIONS_ACCOUNT }}
          SNOWFLAKE_CONNECTIONS_USER: ${{ secrets.SNOWFLAKE_CONNECTIONS_USER }}
          SNOWFLAKE_CONNECTION_PASSWORD: ${{ secrets.SNOWFLAKE_CONNECTION_PASSWORD }}
          SNOWFLAKE_CONNECTIONS_ROLES: ${{ secrets.SNOWFLAKE_CONNECTIONS_ROLES }}
          SNOWFLAKE_CONNECTION_WAREHOUSE: ${{ secrets.SNOWFLAKE_CONNECTION_WAREHOUSE }}
          SNOWFLAKE_CONNECTIONS_DATABASE: ${{ secrets.SNOWFLAKE_CONNECTIONS_DATABASE }}
          SNOWFLAKE_CONNECTIONS_SCHEMA: ${{ secrets.SNOWFLAKE_CONNECTIONS_SCHEMA }}
        run: |
          snow sql -q "ALTER GIT REPOSITORY snowflake_extensions FETCH" --temporary-connection --account $SNOWFLAKE_CONNECTIONS_ACCOUNT --user $SNOWFLAKE_CONNECTIONS_USER --password $SNOWFLAKE_CONNECTION_PASSWORD --role "$SNOWFLAKE_CONNECTIONS_ROLES" --warehouse $SNOWFLAKE_CONNECTION_WAREHOUSE --database $SNOWFLAKE_CONNECTIONS_DATABASE --schema $SNOWFLAKE_CONNECTIONS_SCHEMA
 
          snow sql -q "EXECUTE IMMEDIATE FROM @snowflake_extensions/branches/main/demo_project/sf_deploy_prd.sql" --temporary-connection --account $SNOWFLAKE_CONNECTIONS_ACCOUNT --user $SNOWFLAKE_CONNECTIONS_USER --password $SNOWFLAKE_CONNECTION_PASSWORD --role "$SNOWFLAKE_CONNECTIONS_ROLES" --warehouse $SNOWFLAKE_CONNECTION_WAREHOUSE --database $SNOWFLAKE_CONNECTIONS_DATABASE --schema $SNOWFLAKE_CONNECTIONS_SCHEMA
