name: Actualizar CODEOWNERS

on:
  schedule:
    - cron: '0 0 * * 1'
  workflow_dispatch:

jobs:
  actualizar-codeowners:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0
          persist-credentials: true

      # Instalación de Snowflake CLI
      - name: Snowflake CLI Installation
        uses: Snowflake-Labs/snowflake-cli-action@v1.5
        with:
          cli-version: "latest"
          default-config-file-path: "config.toml"

      - name: Obtener la lista de colaboradores
        env:
          SNOWFLAKE_CONNECTIONS_ACCOUNT: ${{ secrets.SNOWFLAKE_CONNECTIONS_ACCOUNT }}
          SNOWFLAKE_CONNECTIONS_USER: ${{ secrets.SNOWFLAKE_CONNECTIONS_USER }}
          SNOWFLAKE_CONNECTION_PASSWORD: ${{ secrets.SNOWFLAKE_CONNECTION_PASSWORD }}
          SNOWFLAKE_CONNECTIONS_ROLES: ${{ secrets.SNOWFLAKE_CONNECTIONS_ROLES }}
          SNOWFLAKE_CONNECTION_WAREHOUSE: ${{ secrets.SNOWFLAKE_CONNECTION_WAREHOUSE }}
          SNOWFLAKE_CONNECTIONS_DATABASE: ${{ secrets.SNOWFLAKE_CONNECTIONS_DATABASE }}
          SNOWFLAKE_CONNECTIONS_SCHEMA: ${{ secrets.SNOWFLAKE_CONNECTIONS_SCHEMA }}
        run: |
          snow sql -q "SELECT FOLDER_CODEOWNER, USER_GITHUB_NAME FROM GIT_USERS" \
            --temporary-connection \
            --account $SNOWFLAKE_CONNECTIONS_ACCOUNT \
            --user $SNOWFLAKE_CONNECTIONS_USER \
            --password $SNOWFLAKE_CONNECTION_PASSWORD \
            --role $SNOWFLAKE_CONNECTIONS_ROLES \
            --warehouse $SNOWFLAKE_CONNECTION_WAREHOUSE \
            --database $SNOWFLAKE_CONNECTIONS_DATABASE \
            --schema $SNOWFLAKE_CONNECTIONS_SCHEMA \
            --format JSON > resultado_git_users.json

          jq -r '.[] | "\(.FOLDER_CODEOWNER) \(.USER_GITHUB_NAME)"' resultado_git_users.json > .github/CODEOWNERS
            
#      - name: Generar CODEOWNERS dinámico
#        run: |
#          echo "backend/ @Cjaimesg" > .github/CODEOWNERS
#          echo "frontend/ @otro-usuario" >> .github/CODEOWNERS

      - name: Commit & Push si hay cambios
        run: |
          git config user.name "github-actions"
          git config user.email "github-actions@github.com"
          git add .github/CODEOWNERS
          if git diff --cached --quiet; then
            echo "Sin cambios en CODEOWNERS"
          else
            git commit -m "Actualizar CODEOWNERS vía Actions"
            git push
          fi