name: Actualizar CODEOWNERS

on:
  schedule:
    - cron: '0 0 * * 1'
  workflow_dispatch:

jobs:
  actualizar-codeowners:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0
          persist-credentials: true

      - name: Generar CODEOWNERS dinámico
        run: |
          echo "backend/ @Cjaimesg" > .github/CODEOWNERS
          echo "frontend/ @otro-usuario" >> .github/CODEOWNERS

      - name: Commit & Push si hay cambios
        run: |
          git config user.name "github-actions"
          git config user.email "github-actions@github.com"
          git add .github/CODEOWNERS
          if git diff --cached --quiet; then
            echo "Sin cambios en CODEOWNERS"
          else
            git commit -m "Actualizar CODEOWNERS vía Actions"
            git push
          fi